"""remove_lives_alone_prior_readmissions

Revision ID: 4bb69cf4e98a
Revises: 
Create Date: 2026-06-26 21:06:11.330959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4bb69cf4e98a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'lives_alone')
    op.drop_column('patients', 'prior_readmissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('prior_readmissions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('lives_alone', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
