import type { DischargeJob, Patient } from './types'

// ============================================================================
//  SEED ROSTER, the patients shown on first load (ported from the prototype).
//  "Today" in the demo's frame of reference is Jun 27, 2026.
// ============================================================================

export const seedPatients = (): Patient[] => [
  {
    id: 'p_rosa',
    name: 'Rosa Delgado',
    age: 81,
    sex: 'F',
    phone: '(555) 233-1192',
    facility: 'Mercy General',
    dischargeText: 'Yesterday · Day 1',
    dayLine: 'Yesterday · Day 1',
    day: 1,
    dx: 'Community-acquired pneumonia',
    status: 'Flagged · callback',
    statusKind: 'flag',
    hasEpisode: true,
    contactDone: true,
    contactDay: 1,
    visit: { slot: 'Mon, Jun 29 · 2:15 PM', provider: 'Dr. Patel' },
    code: '99496',
    complexity: 'High complexity',
    codeAmount: '$272.68',
    codeRationale:
      'Concerning symptoms on the contact call warrant an expedited face-to-face visit within 7 days; high medical decision-making supports 99496 pending the visit.',
    codeConfirmed: false,
    flag:
      'Patient reports recurrent fever and shortness of breath walking short distances. Flagged for clinical review, the follow-up visit is still scheduled within 7 days, but the care team should review these symptoms and decide if earlier action is needed.',
    ready: false,
    transcript: [
      { who: 'agent', text: "Hi, is this Rosa? This is ContinuaCare calling from Dr. Patel's office about your recent hospital stay." },
      { who: 'patient', text: "Yes, that's me." },
      { who: 'agent', text: "Since you've been home, any new symptoms, fever, trouble breathing, chest pain?" },
      { who: 'patient', text: 'My fever came back last night, and I get really winded just getting to the kitchen.' },
      { who: 'agent', text: "Thank you for telling me, that's important. I'm flagging this for the care team to call you back urgently.", danger: true },
    ],
  },
  {
    id: 'p_harold',
    name: 'Harold Pierce',
    age: 70,
    sex: 'M',
    phone: '(555) 118-7723',
    facility: "St. Anne's Hospital",
    dischargeText: 'Today · Day 0',
    dayLine: 'Today · Day 0',
    day: 0,
    dx: 'CHF exacerbation',
    status: 'Awaiting outreach',
    statusKind: 'new',
    hasEpisode: true,
    contactDone: false,
    contactDay: null,
    visit: null,
    code: null,
    complexity: null,
    codeAmount: null,
    codeRationale: null,
    codeConfirmed: false,
    flag: null,
    ready: false,
    transcript: [],
  },
  {
    id: 'p_yusuf',
    name: 'Yusuf Rahman',
    age: 66,
    sex: 'M',
    phone: '(555) 540-2298',
    facility: 'Riverside Medical Center',
    dischargeText: 'Today · Day 0',
    dayLine: 'Today · Day 0',
    day: 0,
    dx: 'COPD exacerbation',
    status: 'Calling…',
    statusKind: 'calling',
    hasEpisode: true,
    contactDone: false,
    contactDay: null,
    visit: null,
    code: null,
    complexity: null,
    codeAmount: null,
    codeRationale: null,
    codeConfirmed: false,
    flag: null,
    ready: false,
    transcript: [],
  },
  {
    id: 'p_marcus',
    name: 'Marcus Bell',
    age: 68,
    sex: 'M',
    phone: '(555) 660-8890',
    facility: "St. Anne's Hospital",
    dischargeText: '6 days ago · Day 6',
    dayLine: '6 days ago · Day 6',
    day: 6,
    dx: 'CHF exacerbation',
    status: 'Awaiting code confirm',
    statusKind: 'await',
    hasEpisode: true,
    contactDone: true,
    contactDay: 1,
    visit: { slot: 'Wed, Jul 1 · 10:20 AM', provider: 'Dr. Lee' },
    code: '99495',
    complexity: 'Moderate complexity',
    codeAmount: '$201.20',
    codeRationale:
      'Stable on discharge meds, no acute change in condition on the contact call. Moderate medical decision-making supports 99495 (14-day visit window).',
    codeConfirmed: false,
    flag: null,
    ready: false,
    transcript: [
      { who: 'agent', text: "Hi Marcus, this is ContinuaCare from Dr. Lee's office about your discharge." },
      { who: 'patient', text: 'Hi, yes.' },
      { who: 'agent', text: 'Any new or worsening symptoms, swelling, shortness of breath, weight gain?' },
      { who: 'patient', text: 'No, feeling steady. A little tired but okay.' },
      { who: 'agent', text: 'Do you feel comfortable with your medications and the water pill schedule?' },
      { who: 'patient', text: 'Yes, mornings for the water pill.' },
      { who: 'agent', text: 'Great. I have Wednesday 10:20 AM open, shall I book that?' },
      { who: 'patient', text: 'That works.' },
      { who: 'agent', text: 'Booked, Wednesday 10:20 with Dr. Lee. Take care, Marcus.' },
    ],
  },
  {
    id: 'p_james',
    name: 'James Okafor',
    age: 73,
    sex: 'M',
    phone: '(555) 778-3340',
    facility: 'Riverside Medical Center',
    dischargeText: '9 days ago · Day 9',
    dayLine: '9 days ago · Day 9',
    day: 9,
    dx: 'NSTEMI (cardiac)',
    status: 'Appointment scheduled',
    statusKind: 'window',
    hasEpisode: true,
    contactDone: true,
    contactDay: 1,
    visit: { slot: 'Tue, Jun 30 · 11:00 AM', provider: 'Dr. Reyes' },
    code: '99496',
    complexity: 'High complexity',
    codeAmount: '$272.68',
    codeRationale:
      'Recent cardiac event with new anticoagulation and high medical decision-making. Visit booked within 7 days. 99496 confirmed by provider, episode in its 30-day window.',
    codeConfirmed: true,
    flag: null,
    ready: false,
    transcript: [
      { who: 'agent', text: "Hi James, this is ContinuaCare from Dr. Reyes's office regarding your hospitalization." },
      { who: 'patient', text: 'Yes, hello.' },
      { who: 'agent', text: 'Any chest pain, shortness of breath, or new symptoms since you got home?' },
      { who: 'patient', text: 'No chest pain. A bit anxious, but okay.' },
      { who: 'agent', text: 'Are you clear on the new blood thinner and beta blocker?' },
      { who: 'patient', text: 'Yes, the pharmacist went through them.' },
      { who: 'agent', text: "Given the recent event, let's see you quickly, Tuesday 11:00 AM?" },
      { who: 'patient', text: 'That works.' },
      { who: 'agent', text: 'All set, Tuesday 11:00 with Dr. Reyes. Take care, James.' },
    ],
  },
  {
    id: 'p_eleanor',
    name: 'Eleanor Whitfield',
    age: 74,
    sex: 'F',
    phone: '(555) 014-2231',
    facility: 'Mercy General',
    dischargeText: '31 days ago · complete',
    dayLine: '31 days ago · complete',
    day: 31,
    dx: 'COPD exacerbation',
    status: 'Confirm code',
    statusKind: 'await',
    hasEpisode: true,
    contactDone: true,
    contactDay: 1,
    visit: { slot: 'Mon, Jun 1 · 9:40 AM', provider: 'Dr. Sutton' },
    code: '99495',
    complexity: 'Moderate complexity',
    codeAmount: '$201.20',
    codeRationale:
      'Moderate decision-making, stable post-discharge course, visit completed Day 5. 30 days have elapsed with no readmission, episode is complete and ready to bill once the provider confirms the code.',
    codeConfirmed: false,
    flag: null,
    ready: false,
    transcript: [
      { who: 'agent', text: "Hi Eleanor, this is ContinuaCare from Dr. Sutton's office about your recent stay." },
      { who: 'patient', text: 'Oh, hello dear.' },
      { who: 'agent', text: 'Any new breathing trouble or symptoms since you came home?' },
      { who: 'patient', text: "Breathing's been alright with the inhaler." },
      { who: 'agent', text: 'Wonderful. Comfortable with your medications and the prednisone taper?' },
      { who: 'patient', text: 'Yes, my daughter helps me with those.' },
      { who: 'agent', text: "Let's book your follow-up, Friday 9:40 AM with Dr. Sutton?" },
      { who: 'patient', text: "That's fine." },
      { who: 'agent', text: 'Booked. Take good care, Eleanor.' },
    ],
  },
]

// ============================================================================
//  DISCHARGE JOBS, the "Simulate Discharge" button cycles through these three.
// ============================================================================

export const dischargeJobs = (): DischargeJob[] => [
  {
    name: 'Margaret Cho',
    age: 72,
    sex: 'F',
    phone: '(555) 421-8830',
    facility: 'Mercy General',
    dx: 'CHF exacerbation',
    scenario: 'clean',
    code: '99495',
    complexity: 'Moderate complexity',
    codeAmount: '$201.20',
    codeRationale: 'Stable on the contact call, no acute change. Moderate decision-making supports 99495.',
    visit: { slot: 'Thu, Jul 2 · 9:40 AM', provider: 'Dr. Sutton' },
    lines: [
      { who: 'agent', text: "Hi, is this Margaret? This is ContinuaCare calling on behalf of Dr. Sutton's office about your recent hospital stay." },
      { who: 'patient', text: 'Yes, this is she.' },
      { who: 'agent', text: 'Glad I reached you. Since you got home, any new or worsening symptoms, shortness of breath, swelling, chest pain?', chip: 'Symptom check' },
      { who: 'patient', text: 'A little tired, but no, breathing has been okay.' },
      { who: 'agent', text: 'Good to hear. Do you feel comfortable with your medications and how to take them?', chip: 'Medication review' },
      { who: 'patient', text: 'I think so, the water pill in the morning.' },
      { who: 'agent', text: "Perfect. Let's get your follow-up on the books. I have Thursday 9:40 AM or Friday 2:15 PM, which works?", chip: 'Offering slots' },
      { who: 'patient', text: 'Thursday morning is better.' },
      { who: 'agent', text: "Booked, Thursday 9:40. Would you like that with Dr. Sutton specifically, or whoever's available?", chip: 'Booking Thu 9:40' },
      { who: 'patient', text: 'Dr. Sutton if I can.' },
      { who: 'agent', text: 'Done, Thursday 9:40 with Dr. Sutton. Take care, Margaret.', chip: 'Visit booked ✓' },
    ],
  },
  {
    name: 'Robert Hines',
    age: 69,
    sex: 'M',
    phone: '(555) 332-7745',
    facility: "St. Anne's Hospital",
    dx: 'Pneumonia',
    scenario: 'flag',
    lines: [
      { who: 'agent', text: "Hi, is this Robert? ContinuaCare here, calling from Dr. Patel's office about your discharge." },
      { who: 'patient', text: 'Yeah, speaking.' },
      { who: 'agent', text: "Since you've been home, any new symptoms, fever, trouble breathing, chest pain?", chip: 'Symptom check' },
      { who: 'patient', text: "Honestly... my fever's back and I'm pretty winded just walking to the kitchen." },
      { who: 'agent', text: "Thank you for telling me, that's important.", chip: '⚠ Urgent: fever + dyspnea', danger: true },
      { who: 'agent', text: "I'm going to connect you with the care team right now. One moment.", chip: 'Escalating to a human' },
    ],
  },
  {
    name: 'Frank Alvarez',
    age: 77,
    sex: 'M',
    phone: '(555) 661-2093',
    facility: 'Riverside Medical Center',
    dx: 'NSTEMI (cardiac)',
    scenario: 'high',
    code: '99496',
    complexity: 'High complexity',
    codeAmount: '$272.68',
    codeRationale: 'Recent cardiac event, new anticoagulation, high decision-making. Visit booked inside 7 days supports 99496.',
    visit: { slot: 'Sun, Jun 28 · 11:00 AM', provider: 'First available' },
    lines: [
      { who: 'agent', text: "Hi, is this Frank? This is ContinuaCare from Dr. Reyes's office regarding your recent hospitalization." },
      { who: 'patient', text: 'Yes.' },
      { who: 'agent', text: 'Any chest pain, shortness of breath, or new symptoms since you got home?', chip: 'Symptom check' },
      { who: 'patient', text: 'No chest pain. A bit anxious, but okay.' },
      { who: 'agent', text: 'Understood. Are you clear on your medications, the new blood thinner and the beta blocker?', chip: 'Medication review' },
      { who: 'patient', text: 'Yes, the pharmacist went over them.' },
      { who: 'agent', text: 'Given your recent cardiac event we want to see you quickly. Tomorrow 11:00 AM or Wednesday 8:30 AM?', chip: 'Offering slots' },
      { who: 'patient', text: 'Tomorrow works.' },
      { who: 'agent', text: 'Booked, tomorrow 11:00. With Dr. Reyes or first available?', chip: 'Booking tomorrow' },
      { who: 'patient', text: 'First available is fine.' },
      { who: 'agent', text: 'All set, Frank. Take care.', chip: 'Visit booked ✓' },
    ],
  },
]
